version: '3.8'
services:
  esp-rust:
    image: espressif/idf-rust:all_latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    group_add:
      - "166"
      - "20"
      - "dialout"
      - "uucp"
      - "root"
    environment:
      - USER=esp
    command: /bin/bash
